Feture/contenedor footer
Forks-Freneticos/Landing-page-UMSS pull request #1
Opened 2024-05-09 14:17 UTC by jonatan-esprella-lopez

# Hacer el Merge del Pie de pagina "Footer"

Necesito que le des una chequeada y me apruebes el merger.

2024-05-09 18:38 UTC, esther-romero commented on StylesFooter.css
> +.ContenedorFooter{
arreglar nombres de los contenedores, lo correcto es .contenedor-footer

2024-05-09 18:45 UTC, esther-romero requested changes

2024-05-09 18:45 UTC, esther-romero commented on index.html
> +    <link rel="stylesheet" href="./StylesFooter.css">
el archivo de estilos deberia llamarse "styles.css" para no causar conflictos

2024-05-09 18:45 UTC, esther-romero commented on index.html
> +            <p>
etiquetas del mismo nivel, deberían tener un salto de línea de separación.

2024-05-09 18:45 UTC, esther-romero commented on index.html
> +    </Section>
la etiqueta "section" es con minúscula

2024-05-09 18:45 UTC, esther-romero commented on index.html
> +            <img src="./Assets/Images/M.png" alt="Icono de umss" class="LogoUmss">
no es necesario crear un archivo Assets y luego un archivo Images en este caso, con un archivo "images" que guarde todas las imágenes es más que suficiente.

2024-05-10 12:10 UTC, jonatan-esprella-lopez commented on index.html
> +            <p>
Combio realizao con exito :D

2024-05-10 12:13 UTC, merged